// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-smnG8a6v4_HJFXDU4n6UwprRwY0Hvs',
    appId: '1:385301438498:web:6ce9814e62e57f5476aa7b',
    messagingSenderId: '385301438498',
    projectId: 'aquasync-4e17c',
    authDomain: 'aquasync-4e17c.firebaseapp.com',
    storageBucket: 'aquasync-4e17c.firebasestorage.app',
    measurementId: 'G-3VH9S09CFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ff-3qw_BgyOwIMZ6mAWVkmjRgqDpUME',
    appId: '1:385301438498:android:b031373eafaadaf376aa7b',
    messagingSenderId: '385301438498',
    projectId: 'aquasync-4e17c',
    storageBucket: 'aquasync-4e17c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfPXmLpfQppX5BhheufBNvew2_vB_-T94',
    appId: '1:385301438498:ios:d06a14b46a2c76d976aa7b',
    messagingSenderId: '385301438498',
    projectId: 'aquasync-4e17c',
    storageBucket: 'aquasync-4e17c.firebasestorage.app',
    iosBundleId: 'com.example.aquasync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfPXmLpfQppX5BhheufBNvew2_vB_-T94',
    appId: '1:385301438498:ios:d06a14b46a2c76d976aa7b',
    messagingSenderId: '385301438498',
    projectId: 'aquasync-4e17c',
    storageBucket: 'aquasync-4e17c.firebasestorage.app',
    iosBundleId: 'com.example.aquasync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS-smnG8a6v4_HJFXDU4n6UwprRwY0Hvs',
    appId: '1:385301438498:web:0de610868d40b86d76aa7b',
    messagingSenderId: '385301438498',
    projectId: 'aquasync-4e17c',
    authDomain: 'aquasync-4e17c.firebaseapp.com',
    storageBucket: 'aquasync-4e17c.firebasestorage.app',
    measurementId: 'G-L45XFBNMCV',
  );
}
